service: hello-world-pliska

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events:
        - http:
            path: /
            method: get
  hellooo:
    handler: handler.hellooo
    events:
        - http:
            path: /ooo
            method: get
