service: workshop-${self:custom.name}

frameworkVersion: '3'

custom:
  name: pliska

provider:
  name: aws
  runtime: nodejs14.x

functions:
  get-index:
    handler: functions/get-index.handler
    events:
      - http:
          path: /
          method: get
