name: deploy dev

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    # this prevents concurrent builds
    concurrency: dev-environment

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # this is required for authenticating to AWS via the OIDC Provider we set up
    permissions:
      id-token: write
      contents: write

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::993755300009:role/GitHubActionsRole-pliska
          role-session-name: GithubActionsSession

      # - name: cd
      #   run: cd 02-production-ready-serverless

      - name: npm ci
        run: npm ci
        workingdirectory: ./02-production-ready-serverless

      - name: run integration test
        run: npm run test
        workingdirectory: ./02-production-ready-serverless

      - name: deploy to dev
        run: npx sls deploy
        workingdirectory: ./02-production-ready-serverless

      - name: run acceptance tests
        run: npm run acceptance
        workingdirectory: ./02-production-ready-serverless
